sayılar = [35,26,81,64]
sayılar.sort(reverse=True)
print (sayılar)
sayılar.reverse()
print(sayılar)
say = sayılar.count(26)
print(say)
sayılar.pop(3)
print(sayılar)
sayılar.clear()
print(sayılar)
sayılar.append(26)
print(sayılar)
sayılar.append(35)
print(sayılar)
sayılar.append(64)
print(sayılar)
print(sayılar.index(64))
ondalık_sayılar = [1.4,6.8 ]
sayılar.extend(ondalık_sayılar)
print(sayılar)