sayılar = [35,26,81,64]
sayılar.sort(reverse=True)
print(sayılar)
sayılar.reverse()
print(sayılar)
say = sayılar.count(26)
print(say)
sayılar.remove(81)
print(sayılar)
sayılar.clear()
print(sayılar)
sayılar.append(26)
sayılar.append(35)
sayılar.append(64)
print(sayılar)
print(sayılar.index(64))
ondalık_sayılar = [1.4,4.8]
sayılar.extend(ondalık_sayılar)
print(sayılar)