ders = ["B","İ","L","İ","Ş","İ","M"]
ders.sort()
print(ders)
ders.reverse()
print(ders)

say = ders.count("İ")
print(say)
ders.pop(0)
ders.pop(1)
print(ders)
ders.clear()
print(ders)
ders.insert(0,"BİLİM")
print(ders)
yeni_liste = ders.copy()
print(yeni_liste)
ders.clear()
print(ders)
